apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-vault-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd # This forces the backup data onto the Worker HDDs
  resources:
    requests:
      storage: 500Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: prometheus-raw-backup
  namespace: monitoring
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: kube-master-01 # pod must run here to see the local NVMe
          containers:
          - name: backup-worker
            image: instrumentisto/rsync-ssh:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Ensuring destination directory exists..."
              mkdir -p /destination-vault/prometheus-backup
              echo "Starting rsync from NVMe to Longhorn HDD Tier..."
              rsync -rtv --delete /source-nvme/ /destination-vault/prometheus-backup/
              echo "Backup Complete!"
            volumeMounts:
            - mountPath: /source-nvme
              name: nvme-data
              readOnly: true
            - mountPath: /destination-vault
              name: hdd-vault
          restartPolicy: OnFailure
          volumes:
          - name: nvme-data
            hostPath:
              path: /var/lib/kubernetes-data # The local physical NVMe source
          - name: hdd-vault
            persistentVolumeClaim:
              claimName: prometheus-vault-pvc # The managed Longhorn HDD destination
