[masters]
kube-master-01 ansible_host=192.168.1.150 internal_ip=10.0.0.150

[workers]
kube-master-02 ansible_host=192.168.1.151 internal_ip=10.0.0.151
kube-worker-01 ansible_host=192.168.1.160 internal_ip=10.0.0.160
kube-worker-02 ansible_host=192.168.1.161 internal_ip=10.0.0.161
kube-worker-03 ansible_host=192.168.1.162 internal_ip=10.0.0.162

# Define the group 'cluster' by listing its members
[cluster:children]
masters
workers

# NOW you can apply variables to that group
[cluster:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/purplemethodkey
ansible_become=yes
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
