---
- name: Tier 3 - Bulk Archive Storage (NFS) Provisioning
  hosts: kube-master-02
  become: yes
  tasks:
    - name: Install parted utility
      pacman:
        name: parted
        state: present

    - name: Unmount /dev/sda1 if it is currently mounted
      mount:
        path: /mnt/bulk-storage
        state: unmounted
      ignore_errors: yes

    - name: Wipe disk signatures to prevent ghost partitions
      shell: wipefs -af /dev/sda

    - name: Create new GPT layout and partition
      shell: parted -s /dev/sda mklabel gpt mkpart primary ext4 0% 100%

    - name: Notify OS kernel of partition changes
      shell: partprobe /dev/sda

    - name: Format the new HDD partition to ext4
      filesystem:
        fstype: ext4
        dev: /dev/sda1
        force: yes

    - name: Create the mount point directory for Bulk Storage
      file:
        path: /mnt/bulk-storage
        state: directory
        mode: '0777' # Important so NFS clients can read/write

    - name: Mount the HDD and permanently add to /etc/fstab
      mount:
        path: /mnt/bulk-storage
        src: /dev/sda1
        fstype: ext4
        state: mounted
